name: 'AWS S3 Sync Action'
description: 'Sync files to s3 with compare and create cloudfront invalidation.'
author: wxul
inputs:
  aws_bucket_name:
    description: Bucket name
    required: true

  aws_bucket_dir:
    description: Bucket prefix
    required: false

  aws_cloudfront_distribution_id:
    description: Cloudfront distribution id
    required: false

  acl:
    description: ACL (like:public-read, default is empty)
    required: false
    default: private

  compare:
    description: Compare ETag with s3 existed files
    required: false
    default: "true"

  source:
    description: Source file
    required: true

  filename:
    description: Rename file name
    required: false

outputs:
  error_message:
    description: The error message, if an error occurs
  invalidation_id:
    description: Cloudfront invalidation id if Created

runs:
  using: 'node16'
  main: 'lib/index.js'
